language: go

go:
  - 1.3
  - 1.4
  - tip

install:
  - go get gopkg.in/check.v1
  - go get github.com/ugorji/go-msgpack
  - go get github.com/ugorji/go/codec
  - mkdir -p $HOME/gopath/src/gopkg.in/vmihailenco
  - ln -s `pwd` $HOME/gopath/src/gopkg.in/vmihailenco/msgpack.v2
